name: smart-attendance
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.12.8
  - pip=24.2
  - pip:
      - fastapi==0.115.0
      - pydantic==2.9.2
      - pydantic-settings==2.6.0
      - hypercorn==0.17.3
      - uvicorn==0.31.0
      - python-multipart==0.0.12
      - opencv-python==4.10.0.84
      - numpy==1.26.4
      - onnxruntime==1.19.2
      - torch==2.5.0
      - torchvision==0.20.0
      - mlflow==2.17.0
      - sqlalchemy==2.0.35
      - cryptography==43.0.1
      - pyyaml==6.0.2
      - requests==2.32.3
      - httpx==0.27.2
      - python-jose[cryptography]==3.3.0
      - pytest==8.3.3
      - pytest-cov==6.0.0
      - pytest-asyncio==0.24.0
      - mypy==1.11.2
      - black==24.10.0
      - isort==5.13.2
      - ruff==0.7.0
