# Canary rollout manifest (stub)
# TODO: Implement in Module 16

apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: smart-attendance-canary
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: smart-attendance-api
  service:
    port: 80
  analysis:
    interval: 1m
    threshold: 5
    maxWeight: 50
    stepWeight: 10
    metrics:
      - name: request-success-rate
        thresholdRange:
          min: 99
        interval: 1m
      - name: request-duration
        thresholdRange:
          max: 500
        interval: 1m
