# Kubernetes deployment manifest (stub)
# TODO: Implement in Module 16

apiVersion: apps/v1
kind: Deployment
metadata:
  name: smart-attendance-api
  labels:
    app: smart-attendance
spec:
  replicas: 3
  selector:
    matchLabels:
      app: smart-attendance
  template:
    metadata:
      labels:
        app: smart-attendance
    spec:
      containers:
        - name: api
          image: smart-attendance:latest
          ports:
            - containerPort: 8000
          env:
            - name: APP_ENV
              value: "production"
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "2000m"
              memory: "4Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: smart-attendance-service
spec:
  selector:
    app: smart-attendance
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
